from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(640, 439)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(90, 80, 113, 32))
        font = QtGui.QFont()
        font.setFamily("Jaini")
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.progressBar = QtWidgets.QProgressBar(Dialog)
        self.progressBar.setGeometry(QtCore.QRect(140, 380, 361, 40))
        self.progressBar.setProperty("value", 1)
        self.progressBar.setObjectName("progressBar")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(100, 120, 511, 31))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(100, 200, 511, 31))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(90, 170, 113, 32))
        font = QtGui.QFont()
        font.setFamily("Jaini")
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(210, 290, 200, 50))
        font = QtGui.QFont()
        font.setFamily("PSL Ornanong Pro")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(210, 90, 191, 16))
        font = QtGui.QFont()
        font.setFamily("Heiti TC")
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(210, 180, 191, 16))
        font = QtGui.QFont()
        font.setFamily("Heiti TC")
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(100, 250, 451, 31))
        self.label_7.setText("")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")

        self.retranslateUi(Dialog)
        self.pushButton.clicked.connect(Dialog.findDir)
        self.pushButton_2.clicked.connect(Dialog.findDir2)
        self.pushButton_3.clicked.connect(Dialog.go)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "browse"))
        self.pushButton_2.setText(_translate("Dialog", "browse"))
        self.pushButton_3.setText(_translate("Dialog", "FIND IT!"))
        self.label_5.setText(_translate("Dialog", "JPG 폴더 경로를 설정해주세요"))
        self.label_6.setText(_translate("Dialog", "CR2 폴더 경로를 설정해주세요"))

